/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#000000',
        card: '#ffffff',
        'card-foreground': '#000000',
        popover: '#ffffff',
        'popover-foreground': '#000000',
        primary: '#000000',
        'primary-foreground': '#ffffff',
        secondary: '#f8f9fa',
        'secondary-foreground': '#000000',
        muted: '#6c757d',
        'muted-foreground': '#495057',
        accent: '#000000',
        'accent-foreground': '#ffffff',
        destructive: '#dc3545',
        'destructive-foreground': '#ffffff',
        border: '#e9ecef',
        input: '#ffffff',
        ring: 'rgba(0, 0, 0, 0.2)',
        'chart-1': '#000000',
        'chart-2': '#495057',
        'chart-3': '#6c757d',
        'chart-4': '#adb5bd',
        'chart-5': '#dee2e6',
        sidebar: '#ffffff',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#f8f9fa',
        'sidebar-primary-foreground': '#000000',
        'sidebar-accent': '#000000',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#e9ecef',
        'sidebar-ring': 'rgba(0, 0, 0, 0.2)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Space Grotesk', 'serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
}